/* components/index.ts

  Props:  none

  Export: constants as named variables

  Functions:  allow simultaneous export of styles and constants

  Usage: add import statement in any other file and reference colors by name
    import { colors, reusedStyles, values } from '@/constants';

  References:
    Template generated by ChatGPT
*/

export { default as colors } from '@/constants/Colors';
export { default as reusedStyles } from '@/constants/reusedStyles';
export { default as values } from '@/constants/Values';
