/*  constants/index.tsx

  Props: none

  Exports: named constant sections

  Functions:  provide easy access to all styling files and reduce imports

  Usage: import { colors, reusedStyles, values } from '@/constants';

  References:
    Generated by ChatGPT
*/

export { default as colors } from '@/constants/Colors';
export { default as reusedStyles } from '@/constants/reusedStyles';
export { default as values } from '@/constants/Values';
